title: Zaid B. Arif
logo: /assets/Profile_img.png
description: 
Passionate and visionary coder committed to crafting impactful solutions. Thrives on transforming innovative ideas into reality through a combination of rapid learning and efficient coding practices.
show_downloads: false
theme: jekyll-theme-minimal
