title: Zaid B. Arif
logo: /assets/Profile_img.png
description: Enthusiastic and visionary coder wd make a positive difference. Known for fast learning and adaptability, I thrive on turning innovative ideas into reality through the power of code.
show_downloads: false
theme: jekyll-theme-minimal
